spring.application.name=clinic-appointment
server.port=8083
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:808/clinic_db
spring.datasource.username=clinic
spring.datasource.password=Rushi@1229
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA (Hibernate) Configuration
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
