# Spring Application Name
spring.application.name=clinic-appointment

# Api Base Path
server.servlet.context-path=/api/v1

# Server Configuration
server.port=1229

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:8080/clinic_db
spring.datasource.username=clinic
spring.datasource.password=Clinic@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging level
logging.level.root=INFO
logging.level.com.soprasteria.clinic.appointment=debug

logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=ERROR

# Output directory
logging.file.name=logs/cliniclog.log

# Rolling policy (if you don't use XML config)
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=500MB

jwt.expiration.ms=3600000

# Show only WARN and above

# Enable specific endpoints
management.endpoints.web.exposure.include=health,info
# Optionally, customize a base path
management.endpoints.web.base-path=/actuator
management.health.ssl.enabled=false

# Show full health details
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=false

# Enable actuator endpoints in Springdoc
springdoc.show-actuator=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

scheduler.cron.expression=0 0 12 * * ?

